//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountigConsumable
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsInDelivery
    {
        public int id { get; set; }
        public int FK_MaterialCard { get; set; }
        public int FK_Replenishment { get; set; }
        public int MaterialQuantity { get; set; }
    
        public virtual MaterialCard MaterialCard { get; set; }
        public virtual ReplenishmentOfMaterials ReplenishmentOfMaterials { get; set; }
    }
}
