//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountigConsumable
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialCard()
        {
            this.DeliveredMaterial = new HashSet<DeliveredMaterial>();
            this.MaterialsInDelivery = new HashSet<MaterialsInDelivery>();
            this.OrderedMaterial = new HashSet<OrderedMaterial>();
        }
    
        public int id { get; set; }
        public string InventNumber { get; set; }
        public System.DateTime DateOfDelivery { get; set; }
        public Nullable<int> FK_StatusOfMaterial_id { get; set; }
        public int FK_Material { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveredMaterial> DeliveredMaterial { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual StatusOfMaterial StatusOfMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsInDelivery> MaterialsInDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderedMaterial> OrderedMaterial { get; set; }
    }
}
