//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountigConsumable
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialInInventarization
    {
        public int id { get; set; }
        public int FK_Inventarization { get; set; }
        public int FK_Material { get; set; }
        public int Amount { get; set; }
    
        public virtual Inventarization Inventarization { get; set; }
        public virtual Materials Materials { get; set; }
    }
}
