//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountigConsumable
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountingForConsumablesEntities : DbContext
    {
        public static AccountingForConsumablesEntities _Context;
        public AccountingForConsumablesEntities()
            : base("name=AccountingForConsumablesEntities")
        {
        }
        public static AccountingForConsumablesEntities GetContext()
        {
            if (_Context == null)
                _Context = new AccountingForConsumablesEntities();
            return _Context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeliveredMaterial> DeliveredMaterial { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Inventarization> Inventarization { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<MaterialCard> MaterialCard { get; set; }
        public virtual DbSet<MaterialGroup> MaterialGroup { get; set; }
        public virtual DbSet<MaterialInInventarization> MaterialInInventarization { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<MaterialsInDelivery> MaterialsInDelivery { get; set; }
        public virtual DbSet<OperationHystory> OperationHystory { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderedMaterial> OrderedMaterial { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<ReplenishmentOfMaterials> ReplenishmentOfMaterials { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<StatusOfMaterial> StatusOfMaterial { get; set; }
        public virtual DbSet<StatusOfWorker> StatusOfWorker { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfRoom> TypeOfRoom { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<WorkPlace> WorkPlace { get; set; }
    }
}
