//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountigConsumable
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplenishmentOfMaterials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReplenishmentOfMaterials()
        {
            this.MaterialsInDelivery = new HashSet<MaterialsInDelivery>();
        }
    
        public int id { get; set; }
        public int FK_Warehouse { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime DateOfAcceptanceToTheWarehouse { get; set; }
        public int FK_Worker { get; set; }
        public bool Certified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsInDelivery> MaterialsInDelivery { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
