//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountigConsumable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Inventarization = new HashSet<Inventarization>();
            this.OperationHystory = new HashSet<OperationHystory>();
            this.ReplenishmentOfMaterials = new HashSet<ReplenishmentOfMaterials>();
            this.WorkPlace = new HashSet<WorkPlace>();
        }
    
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public int FK_Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int FK_StatusOfWorker { get; set; }
        public int FK_Position { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool CheckFirstVisit { get; set; }
        public byte[] Photo { get; set; }
        public string FIO
        {
            get
            {
                if (FirstName == "All")
                {
                    return FirstName;
                }
                else
                {
                    return LastName + " " + FirstName.Substring(0, 1) + " " + MiddleName.Substring(0, 1);
                }
            }
        }
        public string FIOPostion
        {
            get
            {
                return LastName + " " + FirstName.Substring(0, 1) + " " + MiddleName.Substring(0, 1) + " " + Position.PositionName;
            }
        }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventarization> Inventarization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationHystory> OperationHystory { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplenishmentOfMaterials> ReplenishmentOfMaterials { get; set; }
        public virtual StatusOfWorker StatusOfWorker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPlace> WorkPlace { get; set; }
    }
}
